### ISSUE TITLE
Build errors

### ISSUE THREAD

**Issue by silverua** [Moolt/Unity-Null-Reference-Detection#3]
Hi. Thanks for making this asset. We tried to use it in our project, but ran into some build errors, which I think may be caused by using classes from the UnityEditor namespace outside of the Editor folder. Here's an image of the errors:
![image](https://github.com/Moolt/Unity-Null-Reference-Detection/assets/14848426/50a8acf2-6dc1-4d17-b8c7-4e32069fc848)

**Comment by Moolt** [comment]
Yeah, you're right. Should be fixed now.
