### ISSUE TITLE
Add a check on compile / before play

### ISSUE THREAD

**Issue by cihadturhan** [Moolt/Unity-Null-Reference-Detection#4]
Thank you for the amazing asset. This was exactly what I was looking for. 
Question: is it easy to add a setting that null checks after script compilation or before entering play mode?

I'd prefer it to run automatically because I can forgot to click the menu icon ocassionally.

I'll give a try, might send a PR if it makes sense to you.

Thanks

**Comment by Moolt** [comment]
Hi. I see you've already answered your own question. I added the possibility to check on compilation or before / after entering play mode anyways. You can control when to check for null references in the preferences.

**Comment by cihadturhan-st** [comment]
> Hi. I see you've already answered your own question. I added the possibility to check on compilation or before / after entering play mode anyways. You can control when to check for null references in the preferences.

Thank you! Have a great day
